### PR TITLE
fixed deprecation warnings for julia 0.7

### PR DESCRIPTION
**Pull request by yadongli**
all tests has passed, please review and merge.

### CODE REVIEW

**Comment by o314** [comment]
It seems you need to generate a Project.toml  file.
May be with a Test specific section.

More info here :

- https://discourse.julialang.org/t/travis-ci-fails-for-julia-v0-7-since-test-package-missing/13290/27 
-  https://docs.julialang.org/en/latest/stdlib/Pkg/#Test-specific-dependencies-1

**Comment by yadongli** [comment]
thanks for the pointers, i updated the .travis.yml and the CI test has passed,

**Comment by scls19fr** [comment]
It will be nice if @bicycle1885 could merge this and publish a tag for this version because there is currently no published CLI argument parser library for Julia 0.7/1.0 ([ArgParse.jl](https://github.com/carlobaldassi/ArgParse.jl/issues/68) also need Julia 0.7/1.0 testing)

**Comment by scls19fr** [comment]
Any news @bicycle1885 ?
Pinging also some members of https://github.com/docopt/ @keleshev @edwindj @shabbyrobe @BurntSushi if @bicycle1885 is too busy.

**Comment by scls19fr** [comment]
@yadongli just a small Git/Github tip... when submitting a PR you should do it from an other branch than `master` (a `julia_07_10` branch for example) because if upstream author decide not to merge your PR your master and upstream master won't be sync which is generally not a great idea.

**Comment by staticfloat** [comment]
If @bicycle1885 is too busy to maintain this package, I would be happy to help out.  I know Kenta has not been very responsive on GitHub recently, so if we can spread out the maintenance burden a bit that might help everybody.

**Comment by scls19fr** [comment]
@staticfloat That will be very nice if you could tackle this but one of members of [docopt Github org](https://github.com/docopt) should grant you collaborator access to this repository to speed up things.
Pinging @keleshev @edwindj @shabbyrobe @BurntSushi

**Comment by bicycle1885** [comment]
Hi, I'm very sorry for not being responsive these days, and I think it will continue for a while. Fortunately, @staticfloat has volunteered to maintain this package and so I've added him as an admin. I'm going to get back soon or later but I think co-maintaining the package is a good idea. Thank you very much, @staticfloat!

**Comment by staticfloat** [comment]
Thanks Kenta, I know that life outside of Julia-land can become very busy at times.  :)

I'm going to merge this and tag a new release.  Thanks @yadongli for doing the work of upgrading the syntax.

**Pull request merged**
