### PR TITLE
Add Project.toml, update version + travis setup

### PR DESCRIPTION
**Pull request by rasmushenningsson**
Change from old REQUIRE to new Project.toml.
Bump version to 0.4.1 to prepare for new patch release.
Update travis to run on 1.5 and 1.0.
Add .gitignore (for Manifest.toml).

### CODE REVIEW

**Comment by rasmushenningsson** [comment]
bump :smile:

**Comment by rasmushenningsson** [comment]
bump

**Comment by waldyrious** [comment]
Maybe try pinging @bicycle1885 directly? Or, according to the [commit history](https://github.com/docopt/DocOpt.jl/commits/master), it looks like a few other people have commit rights in this repo, e.g. @r9y9, @staticfloat and @tkelman. Maybe one of them can chime in :)

**Comment by rasmushenningsson** [comment]
I think you just did, thanks! 😄

**Comment by rasmushenningsson** [comment]
Thank you @staticfloat! Would it be possible to make a new release as well?

**Pull request merged**
